### ISSUE TITLE
fake server

### ISSUE THREAD

**Issue by ChrisWillette** [BlackhoefStudios/DropIt#24]
need a fake server so i get working on the hard-coded things

**Comment by ChrisWillette** [comment]
we need a fake database to send requests for project lists and tasks and stuff. i say fake, because xamarin android player doesn't like for-reals network connections, so we need a db of sorts that can be hosted on the dev machines to play nice with the app. i have no idea how to go about that, so i'm pawning that off on you.

**Comment by ChrisWillette** [comment]
And don't ever, EVER, try to mess with the network adapter settings on xamarin android player. it will screw up that version of android for good and then screw up all the others, throwing an opengl error. you can fix the others, but not original. true story.

**Comment by tvand7093** [comment]
Well if it won't let you use the network, you shouldn't even be able to sign into the app...

**Comment by tvand7093** [comment]
I will still create a test server for us to use, but you should be able to hit it using your machines/phones connection... It would be too difficult to utilize a local system.

**Comment by ChrisWillette** [comment]
i just realized that if the connection for the android emulator is actually host-only, then we've got another bug: i'm able to sign in as a new user (in this case name@net.com) and access the list of projects.

**Comment by ChrisWillette** [comment]
and i just settled it once and for all. don't know why the xamarin installer says it's making a host-only connection in virtual box. unless my understanding of host-only connections is completely wrong, it's not host-only. the internet browser works.
